os:
  - linux

language:
  - minimal

services:
  - docker

# Container setup.
before_install:
  - |
    docker build -t ci-image - <<EOF
      FROM jjmerelo/alpine-raku

      USER root
      RUN ["apk", "add", "--no-cache", "bash"]

      # Install pds-companion & optional dependency
      RUN curl --output pds-companion.zip -L 'https://github.com/moretrim/pds-companion/archive/0.2.0-alpha+20200612.zip' \
          && unzip pds-companion.zip                                                                                      \
          && zef install --/test Terminal::ANSIColor                                                                      \
          && cd pds-companion-*                                                                                           \
          && zef install --/test .

      RUN addgroup -S ci-runner && adduser -S ci-runner -G ci-runner

      USER ci-runner
      VOLUME /home/ci-runner/build
      WORKDIR /home/ci-runner/build

      # skip here-document terminator due to Travis silliness; produces a warning
  - docker images

matrix:
  include:
    -
      if: type = pull_request
      name: "Merge Check"
      script: |
        docker run -t                                        \
          --name container-env                               \
          --env TRAVIS_COMMIT_RANGE                          \
          --volume "$TRAVIS_BUILD_DIR":/home/ci-runner/build \
          --entrypoint bash                                  \
          ci-image -c '
            # fail on first error
            set -Eeuo pipefail

            # compute difference
            readarray -d "" pr_files < <(git diff-tree --no-commit-id --name-only -z --diff-filter=AM -r "$TRAVIS_COMMIT_RANGE" -- wild-west/)
            if (( "${#pr_files[@]}" == 0 )) ; then
              echo "No mod files to test."
              exit
            fi

            echo   "## PR: fresh mod files ##"
            printf "    %q\n" "${pr_files[@]}"

            # run static analysis
            vic2-companion --color=always --heartbeat --remarks=opinion --base=wild-west "${pr_files[@]/wild-west\//}"
          '

    -
      if: type = push
      name: "Commit Check"
      script: |
        docker run -t                                        \
          --name container-env                               \
          --volume "$TRAVIS_BUILD_DIR":/home/ci-runner/build \
          --entrypoint bash                                  \
          ci-image -c '
            # fail on first error
            set -Eeuo pipefail

            # compute difference
            readarray -d "" commit_files < <(git diff-tree --no-commit-id --name-only -z --diff-filter=AM -r HEAD -- wild-west/)
            if (( "${#commit_files[@]}" == 0 )) ; then
              echo "No mod files to test."
              exit
            fi

            echo   "## Commit: fresh mod files ##"
            printf "    %q\n" "${commit_files[@]}"

            # run static analysis
            vic2-companion --color=always --heartbeat --remarks=opinion --base=wild-west "${commit_files[@]/wild-west\//}"
          '

    -
      if: type = push
      name: "Branch Check"
      script: |
        docker run -t                                        \
          --name container-env                               \
          --volume "$TRAVIS_BUILD_DIR":/home/ci-runner/build \
          --entrypoint bash                                  \
          ci-image -c '
            # fail on first error
            set -Eeuo pipefail

            # run static analysis
            vic2-companion --color=always --heartbeat --base=wild-west .
          '
